"""
gui/components/utils/validation_helpers.py

Shared helpers for form validation across all data-entry pages.

Usage pattern
-------------
Simple page (only build_form() fields):
    def validate(self):
        return validate_form(MY_FIELDS, self)

Page with warning thresholds:
    def validate(self):
        return validate_form(MY_FIELDS, self, warn_rules=WARNING_RULES)

Page with extra validation (tables, custom widgets, etc.):
    def validate(self):
        result = validate_form(MY_FIELDS, self)
        extra_errors = self._validate_my_table()
        if extra_errors:
            result["errors"].extend(extra_errors)
        return result

Caller checks success as:
    result = page.validate()
    if not result["errors"] and not result["warnings"]:
        # all good

Standard validation flow
------------------------
1. Clear styles       — reset all visual state before re-validating
2. Required checks    — is the field filled at all?         → result["errors"]
3. Range/warn checks  — is the value plausible?             → result["warnings"]
                        (skips fields already in errors)
                        (skips optional fields with no value)
4. Cross-field checks — handled externally by the caller via the extra-validation pattern
5. Return             — {"errors": [...], "warnings": [...]}

Each layer only runs on fields that passed the previous layer:
    required=True,  empty        → error   (stops here, warn skipped)
    required=False, empty        → skip    (neither error nor warning)
    required=any,   value present, in range  → ok
    required=any,   value present, out of range → warning
"""

from PySide6.QtWidgets import (
    QAbstractSpinBox,
    QLineEdit,
)

from .form_builder.form_definitions import FieldDef


# ── Field helpers ─────────────────────────────────────────────────────────────


def field_title(key: str, fields: list) -> str:
    """Return the human-readable title for a field key, falling back to the key."""
    return next(
        (f.title for f in fields if isinstance(f, FieldDef) and f.key == key),
        key,
    )


def _is_required(key: str, fields: list) -> bool:
    """Return True if the field with this key is marked required."""
    return any(
        isinstance(f, FieldDef) and f.key == key and f.required
        for f in fields
    )


def clear_field_styles(fields: list, widget_owner, skip_keys: set = None):
    """Clear validation border styles from all FieldDef widgets."""
    skip = skip_keys or set()
    for f in fields:
        if not isinstance(f, FieldDef) or f.key in skip:
            continue
        widget = getattr(widget_owner, f.key, None)
        if widget:
            widget.setStyleSheet("")


# ── Centralised form validation ───────────────────────────────────────────────


def validate_form(
    fields: list,
    widget_owner,
    warn_rules: dict = None,
    skip_keys: set = None,
) -> dict:
    """
    Standard validation for fields generated by build_form().

    Returns
    -------
    {"errors": [str, ...], "warnings": [str, ...]}
        Both lists empty → validation passed.
        Caller checks: if not result["errors"] and not result["warnings"]
    """
    # ── Step 1: Clear styles ──────────────────────────────────────────────────
    clear_field_styles(fields, widget_owner, skip_keys=skip_keys)
    skip = skip_keys or set()

    # ── Step 2: Required checks ───────────────────────────────────────────────
    errors: list[str] = []
    error_keys: set[str] = set()

    for f in fields:
        if not isinstance(f, FieldDef) or not f.required or f.key in skip:
            continue
        widget = getattr(widget_owner, f.key, None)
        if widget is None:
            errors.append(f"Missing: {f.title}")
            error_keys.add(f.key)
            continue
        if isinstance(widget, QLineEdit) and not widget.text().strip():
            widget.setStyleSheet("border: 1px solid #dc3545;")
            errors.append(f"Missing: {f.title}")
            error_keys.add(f.key)
        # QSpinBox/QDoubleSpinBox: 0 is a valid value, not "missing" — use warn_rules for unusual values
        # QComboBox: always has a selection — no check needed

    # ── Step 3: Range/warn checks ─────────────────────────────────────────────
    # Behaviour by case:
    #   required=True,  failed → in error_keys → skip (keep red)
    #   required=False, empty  → val == 0, not required → skip (no style)
    #   any,            value present → evaluate range normally
    warnings: list[str] = []

    # Merge warn rules: FieldDef.warn takes base, explicit warn_rules override
    effective_warn: dict = {
        f.key: f.warn
        for f in fields
        if isinstance(f, FieldDef) and f.warn is not None
    }
    effective_warn.update(warn_rules or {})

    for key, rule in effective_warn.items():
        low, high = rule[0], rule[1]
        low_msg  = rule[2] if len(rule) > 2 else None
        high_msg = rule[3] if len(rule) > 3 else low_msg  # fall back to low_msg if only one given

        if key in error_keys:
            # Required check already failed — keep red, do not overwrite with orange
            continue
        widget = getattr(widget_owner, key, None)
        if not widget:
            continue
        if not isinstance(widget, QAbstractSpinBox):
            # warn_rules are range checks — only valid for numeric widgets.
            # Skip silently to avoid AttributeError on .value()
            continue
        val = widget.value()

        too_low  = low  is not None and val < low
        too_high = high is not None and val > high

        if too_low:
            label = low_msg if low_msg else f"{field_title(key, fields)} looks unusual ({val})"
            warnings.append(label)
            widget.setStyleSheet("border: 1px solid orange;")
        elif too_high:
            label = high_msg if high_msg else f"{field_title(key, fields)} looks unusual ({val})"
            warnings.append(label)
            widget.setStyleSheet("border: 1px solid orange;")
        else:
            widget.setStyleSheet("")  # passed both checks — clear any stale style

    # ── Step 4 (caller's responsibility): cross-field checks ──────────────────
    # See module docstring for the extra-validation pattern.
    res = {"errors": errors, "warnings": warnings}
    # print(res)
    return res